spring:
  security:
    oauth2:
      client:
        registration:
          spotify:
            client-id: c73804e52f74420a98c80123fc9296d5
            client-secret: d252fb74138f44499419e6442822a53d
            redirect-uri: http://localhost:8080/callback
            provider: spotify
            authorization-grant-type: authorization_code
        provider:
          spotify:
            authorization-uri: https://accounts.spotify.com/authorize
            token-uri: https://accounts.spotify.com/api/token
            user-info-uri: https://api.spotify.com/v1/me
            user-name-attribute: id